"""
Pydantic v2 schemas for the channel stub service.

SendRequest   — what the CRM sends us when dispatching a message
ReceiptPayload — what we POST back to the CRM's receipt webhook
"""

from typing import Optional

from pydantic import BaseModel, Field


class SendRequest(BaseModel):
    """Inbound request from the CRM to send a message."""
    external_id: str                          # UUID generated by CRM, echoed back in receipts
    recipient: str                            # phone number or email
    channel: str                              # "whatsapp", "sms", "email", "rcs"
    message: str
    campaign_id: str
    customer_id: str
    metadata: dict = Field(default_factory=dict)


class ReceiptPayload(BaseModel):
    """Status callback we POST back to the CRM receipt webhook."""
    external_id: str
    status: str                               # "sent", "delivered", "failed", "opened", "clicked"
    timestamp: str                            # ISO 8601
    metadata: dict = Field(default_factory=dict)
